// @ts-nocheck
import { ColorScheme, ColorSchemeProvider, MantineProvider } from '@mantine/core';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import { useState } from "react";
import { NavbarMinimal } from "../components/SideNavbar";
import AuthContextProvider from '../contexts/AuthContext';
import DatabaseContextProvider from '../contexts/DatabaseContext';
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const showHeader = router.pathname === "/login" ? false : true;

  const [colorScheme, setColorScheme] = useState<ColorScheme>('light');
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === 'dark' ? 'light' : 'dark'));

  return (
    <ColorSchemeProvider colorScheme={colorScheme} toggleColorScheme={toggleColorScheme}>
      <MantineProvider theme={{ colorScheme }} withGlobalStyles withNormalizeCSS>
        <AuthContextProvider>
          <DatabaseContextProvider>
            <Head>
              <title>PeopleToProjects</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/icon.ico" />
            </Head>
            {showHeader && <NavbarMinimal />}
            <div style={{ marginLeft: 80 }}>
              <Component {...pageProps} />
            </div>
          </DatabaseContextProvider>
        </AuthContextProvider>
      </MantineProvider>
    </ColorSchemeProvider>
  )
}
